# Generated by Django 3.0 on 2020-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('bookformat', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=30)),
                ('page', models.IntegerField()),
            ],
        ),
    ]
