# Generated by Django 3.0 on 2020-03-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
